---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-cluster-trivy
spec:
  project: infrastructure
  destination:
    namespace: trivy
    server: https://kubernetes.default.svc
  source:
    repoURL: https://aquasecurity.github.io/helm-charts
    chart: trivy-operator
    targetRevision: "0.18.1"
    helm:
      releaseName: trivy
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 5