---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy
spec:
  project: default
  destination:
    namespace: trivy
    server: https://kubernetes.default.svc
  source:
    repoURL: https://aquasecurity.github.io/helm-charts
    chart: trivy-operator
    targetRevision: 0".18.1"
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 5